from sys import executable as python_cmd
import distutils.version
import os.path

Import('*')

if not env['llvm']:
    print 'warning: LLVM disabled: not building swr'
    Return()

swr_arch = 'avx'
SConscript('SConscript-arch', variant_dir='avx', duplicate=0, exports='swr_arch')
swr_arch = 'avx2'
SConscript('SConscript-arch', variant_dir='avx2', duplicate=0, exports='swr_arch')

env = env.Clone()

env.MSVC2008Compat()

source = env.ParseSourceList('Makefile.sources', [
    'CXX_SOURCES'
])

swr = env.ConvenienceLibrary(
	target = 'swr',
	source = source,
	)

env.Alias('swr', swr)

Export('swr')
